[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  PRISMA_GENERATE_DATAPROXY = "true"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"
  PRISMA_CLIENT_ENGINE_TYPE_BINARY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js App Router를 위한 설정
[functions]
  directory = ".next/server/app/api"
  node_bundler = "nft"

# API 라우트 리다이렉트
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
