[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".next/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
