[build]
  command = "npm run build:netlify"
  publish = ".next"

# Next.js App Router를 위한 설정
[functions]
  directory = ".next/server/app/api"
  node_bundler = "nft"



# 개발 환경에서 API 라우트 테스트를 위한 설정
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  PRISMA_GENERATE_DATAPROXY = "false"
  PRISMA_ENGINE_CHECK_EXISTENCE = "false"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"
  PRISMA_CLIENT_ENGINE_TYPE_BINARY = "true"
  PRISMA_ENGINE_PROTOCOL = "binary"
  PRISMA_DISABLE_QUERY_ENGINE_TYPE_BINARY = "false"
  PRISMA_DISABLE_QUERY_ENGINE_TYPE_LIBRARY = "true"
  # Supabase 설정 (실제 값은 Netlify 대시보드에서 설정)
  # SUPABASE_DATABASE_URL = "your-supabase-database-url"
  # NEXT_PUBLIC_SUPABASE_URL = "your-supabase-project-url"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[[plugins]]
  package = "@netlify/plugin-nextjs"
