[build]
  command = "npm run build:netlify"
  publish = ".next"

# Next.js App Router를 위한 설정
[functions]
  directory = ".next/server/app/api"
  node_bundler = "nft"

# 개발 환경에서 API 라우트 테스트를 위한 설정
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
